services:
  - type: worker
    name: NickAuCriptoBot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python3 bot.py
    plan: free
    envVars:
      - key: TELEGRAM_TOKEN
        value: 8092726351:AAHTWskkaxW5WyP0mfGvMOIpEXGWcP_Edbk
